use a more proper name for input arg
Summary:
the input argument `package_dir` is a bit confusing because it suggests that this is the directory where the package lives. However, what this argument really takes is the entire path of the package.

For example, this command failed
```
python3.8 -m onedocker.script.cli upload --config=./config.yml --package_name=private_lift/pcf2_lift --package_dir=./

......
  File "/Users/yigezhu/Library/Python/3.8/lib/python/site-packages/onedocker/repository/onedocker_package.py", line 24, in upload
    self.storage_svc.copy(source, package_path)
  File "/Users/yigezhu/Library/Python/3.8/lib/python/site-packages/fbpcp/service/storage_s3.py", line 64, in copy
    raise ValueError(f"Source {source} is a folder. Use --recursive")
ValueError: Source . is a folder. Use --recursive
```
while this worked:
```
python3.8 -m onedocker.script.cli upload --config=./config.yml --package_name=private_lift/pcf2_lift --package_dir=./pcf2_lift
```
## Next Step
We should probably add in the doc string for what each argument means to make it more user-friendly. I can do this in another diff.

Differential Revision: D38913925

fbshipit-source-id: 018506734d77dee9ec2d05e70fb4039da8903b4b